In [16]:
# https://github.com/jukyellow/algoTrade/blob/master/ch04/4.3%20%EC%A0%88%EB%8C%80%EB%AA%A8%EB%A9%98%ED%85%80.ipynb

In [ ]:
# 절대 모멘텀 전략
# 최근 N개월 동안 수익률이 양수이면 매수하고, 음수이면 공매도하는 전략
#

In [2]:
import pandas as pd
import numpy as np
import datetime

read_df = pd.read_csv('SPY.csv')
read_df.head()

         Date      Open      High       Low     Close  Adj Close   Volume
0  1993-01-29  43.96875  43.96875  43.75000  43.93750  26.706757  1003200
1  1993-02-01  43.96875  44.25000  43.96875  44.25000  26.896694   480500
2  1993-02-02  44.21875  44.37500  44.12500  44.34375  26.953669   201300
3  1993-02-03  44.40625  44.84375  44.37500  44.81250  27.238594   529400
4  1993-02-04  44.96875  45.09375  44.46875  45.00000  27.352570   531500

In [3]:
price_df = read_df.loc[:,['Date','Adj Close']].copy()
price_df.head()

         Date  Adj Close
0  1993-01-29  26.706757
1  1993-02-01  26.896694
2  1993-02-02  26.953669
3  1993-02-03  27.238594
4  1993-02-04  27.352570

In [4]:
price_df['STD_YM']= price_df['Date'].map(lambda x : datetime.datetime.strptime(x, '%Y-%m-%d')\
                                         .strftime('%Y-%m'))
price_df.head()

         Date  Adj Close   STD_YM
0  1993-01-29  26.706757  1993-01
1  1993-02-01  26.896694  1993-02
2  1993-02-02  26.953669  1993-02
3  1993-02-03  27.238594  1993-02
4  1993-02-04  27.352570  1993-02

In [6]:
month_list = price_df['STD_YM'].unique()
month_list

array(['1993-01', '1993-02', '1993-03', '1993-04', '1993-05', '1993-06',
       '1993-07', '1993-08', '1993-09', '1993-10', '1993-11', '1993-12',
       '1994-01', '1994-02', '1994-03', '1994-04', '1994-05', '1994-06',
       '1994-07', '1994-08', '1994-09', '1994-10', '1994-11', '1994-12',
       '1995-01', '1995-02', '1995-03', '1995-04', '1995-05', '1995-06',
       '1995-07', '1995-08', '1995-09', '1995-10', '1995-11', '1995-12',
       '1996-01', '1996-02', '1996-03', '1996-04', '1996-05', '1996-06',
       '1996-07', '1996-08', '1996-09', '1996-10', '1996-11', '1996-12',
       '1997-01', '1997-02', '1997-03', '1997-04', '1997-05', '1997-06',
       '1997-07', '1997-08', '1997-09', '1997-10', '1997-11', '1997-12',
       '1998-01', '1998-02', '1998-03', '1998-04', '1998-05', '1998-06',
       '1998-07', '1998-08', '1998-09', '1998-10', '1998-11', '1998-12',
       '1999-01', '1999-02', '1999-03', '1999-04', '1999-05', '1999-06',
       '1999-07', '1999-08', '1999-09', '1999-10', '1999-11', '1999-12',
       '2000-01', '2000-02', '2000-03', '2000-04', '2000-05', '2000-06',
       '2000-07', '2000-08', '2000-09', '2000-10', '2000-11', '2000-12',
       '2001-01', '2001-02', '2001-03', '2001-04', '2001-05', '2001-06',
       '2001-07', '2001-08', '2001-09', '2001-10', '2001-11', '2001-12',
       '2002-01', '2002-02', '2002-03', '2002-04', '2002-05', '2002-06',
       '2002-07', '2002-08', '2002-09', '2002-10', '2002-11', '2002-12',
       '2003-01', '2003-02', '2003-03', '2003-04', '2003-05', '2003-06',
       '2003-07', '2003-08', '2003-09', '2003-10', '2003-11', '2003-12',
       '2004-01', '2004-02', '2004-03', '2004-04', '2004-05', '2004-06',
       '2004-07', '2004-08', '2004-09', '2004-10', '2004-11', '2004-12',
       '2005-01', '2005-02', '2005-03', '2005-04', '2005-05', '2005-06',
       '2005-07', '2005-08', '2005-09', '2005-10', '2005-11', '2005-12',
       '2006-01', '2006-02', '2006-03', '2006-04', '2006-05', '2006-06',
       '2006-07', '2006-08', '2006-09', '2006-10', '2006-11', '2006-12',
       '2007-01', '2007-02', '2007-03', '2007-04', '2007-05', '2007-06',
       '2007-07', '2007-08', '2007-09', '2007-10', '2007-11', '2007-12',
       '2008-01', '2008-02', '2008-03', '2008-04', '2008-05', '2008-06',
       '2008-07', '2008-08', '2008-09', '2008-10', '2008-11', '2008-12',
       '2009-01', '2009-02', '2009-03', '2009-04', '2009-05', '2009-06',
       '2009-07', '2009-08', '2009-09', '2009-10', '2009-11', '2009-12',
       '2010-01', '2010-02', '2010-03', '2010-04', '2010-05', '2010-06',
       '2010-07', '2010-08', '2010-09', '2010-10', '2010-11', '2010-12',
       '2011-01', '2011-02', '2011-03', '2011-04', '2011-05', '2011-06',
       '2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12',
       '2012-01', '2012-02', '2012-03', '2012-04', '2012-05', '2012-06',
       '2012-07', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-07', '2013-08', '2013-09', '2013-10', '2013-11', '2013-12',
       '2014-01', '2014-02', '2014-03', '2014-04', '2014-05', '2014-06',
       '2014-07', '2014-08', '2014-09', '2014-10', '2014-11', '2014-12',
       '2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06',
       '2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
       '2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06',
       '2016-07', '2016-08', '2016-09', '2016-10', '2016-11', '2016-12',
       '2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06',
       '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12',
       '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06',
       '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12',
       '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06'],
      dtype=object)

In [8]:
#월말 데이터 추출
month_last_df = pd.DataFrame()
for m in month_list:
    # 기준년월에 맞는 인덱스의 가장 마지막 날짜 row를 데이터 프레임에 추가한다
    month_last_df = month_last_df.append(price_df.loc[price_df[price_df['STD_YM'] == m].index[-1] , : ])

month_last_df.set_index(['Date'],inplace=True)
month_last_df.head(20)

            Adj Close   STD_YM
Date
1993-01-29  26.706757  1993-01
1993-02-26  26.991682  1993-02
1993-03-31  27.596252  1993-03
1993-04-30  26.890142  1993-04
1993-05-28  27.615356  1993-05
1993-06-30  27.714964  1993-06
1993-07-30  27.580431  1993-07
1993-08-31  28.637531  1993-08
1993-09-30  28.429131  1993-09
1993-10-29  28.990005  1993-10
1993-11-30  28.680576  1993-11
1993-12-31  29.032679  1993-12
1994-01-31  30.045223  1994-01
1994-02-28  29.168985  1994-02
1994-03-31  27.946764  1994-03
1994-04-29  28.260098  1994-04
1994-05-31  28.710556  1994-05
1994-06-30  28.052668  1994-06
1994-07-29  28.959522  1994-07
1994-08-31  30.063478  1994-08

In [9]:
month_last_df['BF_1M_Adj Close'] = month_last_df.shift(1)['Adj Close']
month_last_df['BF_12M_Adj Close'] = month_last_df.shift(12)['Adj Close']
month_last_df.fillna(0, inplace=True)
month_last_df.head(15)

            Adj Close   STD_YM  BF_1M_Adj Close  BF_12M_Adj Close
Date
1993-01-29  26.706757  1993-01         0.000000          0.000000
1993-02-26  26.991682  1993-02        26.706757          0.000000
1993-03-31  27.596252  1993-03        26.991682          0.000000
1993-04-30  26.890142  1993-04        27.596252          0.000000
1993-05-28  27.615356  1993-05        26.890142          0.000000
1993-06-30  27.714964  1993-06        27.615356          0.000000
1993-07-30  27.580431  1993-07        27.714964          0.000000
1993-08-31  28.637531  1993-08        27.580431          0.000000
1993-09-30  28.429131  1993-09        28.637531          0.000000
1993-10-29  28.990005  1993-10        28.429131          0.000000
1993-11-30  28.680576  1993-11        28.990005          0.000000
1993-12-31  29.032679  1993-12        28.680576          0.000000
1994-01-31  30.045223  1994-01        29.032679         26.706757
1994-02-28  29.168985  1994-02        30.045223         26.991682
1994-03-31  27.946764  1994-03        29.168985         27.596252

In [10]:
book = price_df.copy()
book.set_index(['Date'],inplace=True)
book['trade'] = ''
book.head()

            Adj Close   STD_YM trade
Date
1993-01-29  26.706757  1993-01
1993-02-01  26.896694  1993-02
1993-02-02  26.953669  1993-02
1993-02-03  27.238594  1993-02
1993-02-04  27.352570  1993-02

In [11]:
#trading 부분.
#12개월 전 종가 대비 1개월전 종가 수익률 계산, 0이상이면 매수!

ticker = 'SPY'
for x in month_last_df.index:
    signal = ''
    # 절대 모멘텀을 계산한다. 
    momentum_index = month_last_df.loc[x,'BF_1M_Adj Close'] / month_last_df.loc[x,'BF_12M_Adj Close'] -1
    # 절대 모멘텀 지표 True / False를 판단한다.
    flag = True if ((momentum_index > 0.0) and (momentum_index != np.inf) and (momentum_index != -np.inf))\
    else False \
    and True
    if flag :
        signal = 'buy ' + ticker # 절대 모멘텀 지표가 Positive이면 매수 후 보유.
    print('날짜 : ',x,' 모멘텀 인덱스 : ',momentum_index, 'flag : ',flag ,'signal : ',signal)
    book.loc[x:,'trade'] = signal

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in double_scalars

날짜 :  1993-01-29  모멘텀 인덱스 :  nan flag :  False signal :
날짜 :  1993-02-26  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-03-31  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-04-30  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-05-28  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-06-30  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-07-30  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-08-31  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-09-30  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-10-29  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-11-30  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1993-12-31  모멘텀 인덱스 :  inf flag :  False signal :
날짜 :  1994-01-31  모멘텀 인덱스 :  0.08709114326385636 flag :  True signal :  buy SPY
날짜 :  1994-02-28  모멘텀 인덱스 :  0.1131289632117034 flag :  True signal :  buy SPY
날짜 :  1994-03-31  모멘텀 인덱스 :  0.05699081889816027 flag :  True signal :  buy SPY
날짜 :  1994-04-29  모멘텀 인덱스 :  0.03929402827251738 flag :  True signal :  buy SPY
날짜 :  1994-05-31  모멘텀 인덱스 :  0.02334722753528884 flag :  True signal :  buy SPY
날짜 :  1994-06-30  모멘텀 인덱스 :  0.0359225435039352 flag :  True signal :  buy SPY
날짜 :  1994-07-29  모멘텀 인덱스 :  0.017122176227050145 flag :  True signal :  buy SPY
날짜 :  1994-08-31  모멘텀 인덱스 :  0.011243671809556322 flag :  True signal :  buy SPY
날짜 :  1994-09-30  모멘텀 인덱스 :  0.057488461395461155 flag :  True signal :  buy SPY
날짜 :  1994-10-31  모멘텀 인덱스 :  0.010839080572769833 flag :  True signal :  buy SPY
날짜 :  1994-11-30  모멘텀 인덱스 :  0.05078925193134176 flag :  True signal :  buy SPY
날짜 :  1994-12-30  모멘텀 인덱스 :  -0.0032853668102759137 flag :  False signal :
날짜 :  1995-01-31  모멘텀 인덱스 :  -0.029861319385114715 flag :  False signal :
날짜 :  1995-02-28  모멘텀 인덱스 :  0.032865284822217955 flag :  True signal :  buy SPY
날짜 :  1995-03-31  모멘텀 인덱스 :  0.12203119473868229 flag :  True signal :  buy SPY
날짜 :  1995-04-28  모멘텀 인덱스 :  0.14048928634288527 flag :  True signal :  buy SPY
날짜 :  1995-05-31  모멘텀 인덱스 :  0.1558500295152765 flag :  True signal :  buy SPY
날짜 :  1995-06-30  모멘텀 인덱스 :  0.2298882944039402 flag :  True signal :  buy SPY
날짜 :  1995-07-31  모멘텀 인덱스 :  0.21547638113640155 flag :  True signal :  buy SPY
날짜 :  1995-08-31  모멘텀 인덱스 :  0.20850348718800915 flag :  True signal :  buy SPY
날짜 :  1995-09-29  모멘텀 인덱스 :  0.24533437664118818 flag :  True signal :  buy SPY
날짜 :  1995-10-31  모멘텀 인덱스 :  0.2622262270126188 flag :  True signal :  buy SPY
날짜 :  1995-11-30  모멘텀 인덱스 :  0.3107041514867179 flag :  True signal :  buy SPY
날짜 :  1995-12-29  모멘텀 인덱스 :  0.3591065990627911 flag :  True signal :  buy SPY
날짜 :  1996-01-31  모멘텀 인덱스 :  0.3356030105519079 flag :  True signal :  buy SPY
날짜 :  1996-02-29  모멘텀 인덱스 :  0.3288890718704234 flag :  True signal :  buy SPY
날짜 :  1996-03-29  모멘텀 인덱스 :  0.2970106519822828 flag :  True signal :  buy SPY
날짜 :  1996-04-30  모멘텀 인덱스 :  0.28138450220591493 flag :  True signal :  buy SPY
날짜 :  1996-05-31  모멘텀 인덱스 :  0.2458843994930333 flag :  True signal :  buy SPY
날짜 :  1996-06-28  모멘텀 인덱스 :  0.24890133031284578 flag :  True signal :  buy SPY
날짜 :  1996-07-31  모멘텀 인덱스 :  0.22065642297338384 flag :  True signal :  buy SPY
날짜 :  1996-08-30  모멘텀 인덱스 :  0.16063771790999315 flag :  True signal :  buy SPY
날짜 :  1996-09-30  모멘텀 인덱스 :  0.134898444837668 flag :  True signal :  buy SPY
날짜 :  1996-10-31  모멘텀 인덱스 :  0.20183926834030808 flag :  True signal :  buy SPY
날짜 :  1996-11-29  모멘텀 인덱스 :  0.18786047324562904 flag :  True signal :  buy SPY
날짜 :  1996-12-31  모멘텀 인덱스 :  0.25483633160195907 flag :  True signal :  buy SPY
날짜 :  1997-01-31  모멘텀 인덱스 :  0.1828893537778904 flag :  True signal :  buy SPY
날짜 :  1997-02-28  모멘텀 인덱스 :  0.2519814502721125 flag :  True signal :  buy SPY
날짜 :  1997-03-31  모멘텀 인덱스 :  0.2425622316311724 flag :  True signal :  buy SPY
날짜 :  1997-04-30  모멘텀 인덱스 :  0.17496660758800742 flag :  True signal :  buy SPY
날짜 :  1997-05-30  모멘텀 인덱스 :  0.22081040023661025 flag :  True signal :  buy SPY
날짜 :  1997-06-30  모멘텀 인덱스 :  0.28662372197117003 flag :  True signal :  buy SPY
날짜 :  1997-07-31  모멘텀 인덱스 :  0.4025316433580961 flag :  True signal :  buy SPY
날짜 :  1997-08-29  모멘텀 인덱스 :  0.48509925111569396 flag :  True signal :  buy SPY
날짜 :  1997-09-30  모멘텀 인덱스 :  0.33365289973216505 flag :  True signal :  buy SPY
날짜 :  1997-10-31  모멘텀 인덱스 :  0.3540117256722266 flag :  True signal :  buy SPY
날짜 :  1997-11-28  모멘텀 인덱스 :  0.23096826751662536 flag :  True signal :  buy SPY
날짜 :  1997-12-31  모멘텀 인덱스 :  0.3097720848335761 flag :  True signal :  buy SPY
날짜 :  1998-01-30  모멘텀 인덱스 :  0.2570811069716532 flag :  True signal :  buy SPY
날짜 :  1998-02-27  모멘텀 인덱스 :  0.2612069906434109 flag :  True signal :  buy SPY
날짜 :  1998-03-31  모멘텀 인덱스 :  0.41085143203534424 flag :  True signal :  buy SPY
날짜 :  1998-04-30  모멘텀 인덱스 :  0.39250210060554336 flag :  True signal :  buy SPY
날짜 :  1998-05-29  모멘텀 인덱스 :  0.326472093512296 flag :  True signal :  buy SPY
날짜 :  1998-06-30  모멘텀 인덱스 :  0.2476413534461983 flag :  True signal :  buy SPY
날짜 :  1998-07-31  모멘텀 인덱스 :  0.20522704822675064 flag :  True signal :  buy SPY
날짜 :  1998-08-31  모멘텀 인덱스 :  0.25389559989508625 flag :  True signal :  buy SPY
날짜 :  1998-09-30  모멘텀 인덱스 :  0.027459451827657633 flag :  True signal :  buy SPY
날짜 :  1998-10-30  모멘텀 인덱스 :  0.12029813448586624 flag :  True signal :  buy SPY
날짜 :  1998-11-30  모멘텀 인덱스 :  0.1660121511966206 flag :  True signal :  buy SPY
날짜 :  1998-12-31  모멘텀 인덱스 :  0.2079018659454548 flag :  True signal :  buy SPY
날짜 :  1999-01-29  모멘텀 인덱스 :  0.27056222182679024 flag :  True signal :  buy SPY
날짜 :  1999-02-26  모멘텀 인덱스 :  0.23008030777830268 flag :  True signal :  buy SPY
날짜 :  1999-03-31  모멘텀 인덱스 :  0.13525200948100213 flag :  True signal :  buy SPY
날짜 :  1999-04-30  모멘텀 인덱스 :  0.16739577288826757 flag :  True signal :  buy SPY
날짜 :  1999-05-28  모멘텀 인덱스 :  0.2374272505944519 flag :  True signal :  buy SPY
날짜 :  1999-06-30  모멘텀 인덱스 :  0.15975743083068417 flag :  True signal :  buy SPY
날짜 :  1999-07-30  모멘텀 인덱스 :  0.24075032604916347 flag :  True signal :  buy SPY
날짜 :  1999-08-31  모멘텀 인덱스 :  0.3998979194169203 flag :  True signal :  buy SPY
날짜 :  1999-09-30  모멘텀 인덱스 :  0.30932234887057675 flag :  True signal :  buy SPY
날짜 :  1999-10-29  모멘텀 인덱스 :  0.18407018687317023 flag :  True signal :  buy SPY
날짜 :  1999-11-30  모멘텀 인덱스 :  0.19348727916142772 flag :  True signal :  buy SPY
날짜 :  1999-12-31  모멘텀 인덱스 :  0.13885401178361922 flag :  True signal :  buy SPY
날짜 :  2000-01-31  모멘텀 인덱스 :  0.1629287352931703 flag :  True signal :  buy SPY
날짜 :  2000-02-29  모멘텀 인덱스 :  0.1416406982810301 flag :  True signal :  buy SPY
날짜 :  2000-03-31  모멘텀 인덱스 :  0.07949332098817186 flag :  True signal :  buy SPY
날짜 :  2000-04-28  모멘텀 인덱스 :  0.14079110728297395 flag :  True signal :  buy SPY
날짜 :  2000-05-31  모멘텀 인덱스 :  0.12648388410144706 flag :  True signal :  buy SPY
날짜 :  2000-06-30  모멘텀 인덱스 :  0.05059200486599513 flag :  True signal :  buy SPY
날짜 :  2000-07-31  모멘텀 인덱스 :  0.10556572728547886 flag :  True signal :  buy SPY
날짜 :  2000-08-31  모멘텀 인덱스 :  0.09387178871289503 flag :  True signal :  buy SPY
날짜 :  2000-09-29  모멘텀 인덱스 :  0.19197161097485949 flag :  True signal :  buy SPY
날짜 :  2000-10-31  모멘텀 인덱스 :  0.058735545306240144 flag :  True signal :  buy SPY
날짜 :  2000-11-30  모멘텀 인덱스 :  0.036523261173445176 flag :  True signal :  buy SPY
날짜 :  2000-12-29  모멘텀 인덱스 :  -0.09267296744937004 flag :  False signal :
날짜 :  2001-01-31  모멘텀 인덱스 :  -0.05012325105256776 flag :  False signal :
날짜 :  2001-02-28  모멘텀 인덱스 :  0.007446991068039255 flag :  True signal :  buy SPY
날짜 :  2001-03-30  모멘텀 인덱스 :  -0.16917045042397105 flag :  False signal :
날짜 :  2001-04-30  모멘텀 인덱스 :  -0.18718121676806088 flag :  False signal :
날짜 :  2001-05-31  모멘텀 인덱스 :  -0.10364048057718267 flag :  False signal :
날짜 :  2001-06-29  모멘텀 인덱스 :  -0.12586940788372103 flag :  False signal :
날짜 :  2001-07-31  모멘텀 인덱스 :  -0.13308711358162006 flag :  False signal :
날짜 :  2001-08-31  모멘텀 인덱스 :  -0.19455458952664906 flag :  False signal :
날짜 :  2001-09-28  모멘텀 인덱스 :  -0.198364119006334 flag :  False signal :
날짜 :  2001-10-31  모멘텀 인덱스 :  -0.2603419351418189 flag :  False signal :
날짜 :  2001-11-30  모멘텀 인덱스 :  -0.19026071995438676 flag :  False signal :
날짜 :  2001-12-31  모멘텀 인덱스 :  -0.12253351510832522 flag :  False signal :
날짜 :  2002-01-31  모멘텀 인덱스 :  -0.15514670371310524 flag :  False signal :
날짜 :  2002-02-28  모멘텀 인덱스 :  -0.07521159583105719 flag :  False signal :
날짜 :  2002-03-28  모멘텀 인덱스 :  -0.03788508276503744 flag :  False signal :
날짜 :  2002-04-30  모멘텀 인덱스 :  -0.08412708378510303 flag :  False signal :
날짜 :  2002-05-31  모멘텀 인덱스 :  -0.13252757391452596 flag :  False signal :
날짜 :  2002-06-28  모멘텀 인덱스 :  -0.11662492127557567 flag :  False signal :
날짜 :  2002-07-31  모멘텀 인덱스 :  -0.17339636301358285 flag :  False signal :
날짜 :  2002-08-30  모멘텀 인덱스 :  -0.19052033782512823 flag :  False signal :
날짜 :  2002-09-30  모멘텀 인덱스 :  -0.11257399325975292 flag :  False signal :
날짜 :  2002-10-31  모멘텀 인덱스 :  -0.2158338336604182 flag :  False signal :
날짜 :  2002-11-29  모멘텀 인덱스 :  -0.21270106712070247 flag :  False signal :
날짜 :  2002-12-31  모멘텀 인덱스 :  -0.16882736059495673 flag :  False signal :
날짜 :  2003-01-31  모멘텀 인덱스 :  -0.20808696296650497 flag :  False signal :
날짜 :  2003-02-28  모멘텀 인덱스 :  -0.21345560528366037 flag :  False signal :
날짜 :  2003-03-31  모멘텀 인덱스 :  -0.24904281119008875 flag :  False signal :
날짜 :  2003-04-30  모멘텀 인덱스 :  -0.20096722167191305 flag :  False signal :
날짜 :  2003-05-30  모멘텀 인덱스 :  -0.12818698595654376 flag :  False signal :
날짜 :  2003-06-30  모멘텀 인덱스 :  -0.0070957491566933095 flag :  False signal :
날짜 :  2003-07-31  모멘텀 인덱스 :  0.08934119393133533 flag :  True signal :  buy SPY
날짜 :  2003-08-29  모멘텀 인덱스 :  0.1014875729611373 flag :  True signal :  buy SPY
날짜 :  2003-09-30  모멘텀 인덱스 :  0.25588947964493025 flag :  True signal :  buy SPY
날짜 :  2003-10-31  모멘텀 인덱스 :  0.14775073077108547 flag :  True signal :  buy SPY
날짜 :  2003-11-28  모멘텀 인덱스 :  0.13893660722746137 flag :  True signal :  buy SPY
날짜 :  2003-12-31  모멘텀 인덱스 :  0.2204134014119239 flag :  True signal :  buy SPY
날짜 :  2004-01-30  모멘텀 인덱스 :  0.31413617388303905 flag :  True signal :  buy SPY
날짜 :  2004-02-27  모멘텀 인덱스 :  0.3584271712268199 flag :  True signal :  buy SPY
날짜 :  2004-03-31  모멘텀 인덱스 :  0.3739215632998336 flag :  True signal :  buy SPY
날짜 :  2004-04-30  모멘텀 인덱스 :  0.2499625808431758 flag :  True signal :  buy SPY
날짜 :  2004-05-28  모멘텀 인덱스 :  0.16256052716440927 flag :  True signal :  buy SPY
날짜 :  2004-06-30  모멘텀 인덱스 :  0.1700048992100518 flag :  True signal :  buy SPY
날짜 :  2004-07-30  모멘텀 인덱스 :  0.17055017567760822 flag :  True signal :  buy SPY
날짜 :  2004-08-31  모멘텀 인덱스 :  0.10994295484351624 flag :  True signal :  buy SPY
날짜 :  2004-09-30  모멘텀 인덱스 :  0.1249156357876493 flag :  True signal :  buy SPY
날짜 :  2004-10-29  모멘텀 인덱스 :  0.07847881178635396 flag :  True signal :  buy SPY
날짜 :  2004-11-30  모멘텀 인덱스 :  0.08057314863102172 flag :  True signal :  buy SPY
날짜 :  2004-12-31  모멘텀 인덱스 :  0.07461142625417594 flag :  True signal :  buy SPY
날짜 :  2005-01-31  모멘텀 인덱스 :  0.08551917692642741 flag :  True signal :  buy SPY
날짜 :  2005-02-28  모멘텀 인덱스 :  0.04697276096888614 flag :  True signal :  buy SPY
날짜 :  2005-03-31  모멘텀 인덱스 :  0.08320591064412142 flag :  True signal :  buy SPY
날짜 :  2005-04-29  모멘텀 인덱스 :  0.0838994142851599 flag :  True signal :  buy SPY
날짜 :  2005-05-31  모멘텀 인덱스 :  0.045687368191337674 flag :  True signal :  buy SPY
날짜 :  2005-06-30  모멘텀 인덱스 :  0.059776742395015736 flag :  True signal :  buy SPY
날짜 :  2005-07-29  모멘텀 인덱스 :  0.0967170502846908 flag :  True signal :  buy SPY
날짜 :  2005-08-31  모멘텀 인덱스 :  0.1359117281100808 flag :  True signal :  buy SPY
날짜 :  2005-09-30  모멘텀 인덱스 :  0.11408081305839479 flag :  True signal :  buy SPY
날짜 :  2005-10-31  모멘텀 인덱스 :  0.10873653834111807 flag :  True signal :  buy SPY
날짜 :  2005-11-30  모멘텀 인덱스 :  0.03637662240330064 flag :  True signal :  buy SPY
날짜 :  2005-12-30  모멘텀 인덱스 :  0.05029196750928522 flag :  True signal :  buy SPY
날짜 :  2006-01-31  모멘텀 인덱스 :  0.07232451451312616 flag :  True signal :  buy SPY
날짜 :  2006-02-28  모멘텀 인덱스 :  0.07559186572521726 flag :  True signal :  buy SPY
날짜 :  2006-03-31  모멘텀 인덱스 :  0.10190707946493216 flag :  True signal :  buy SPY
날짜 :  2006-04-28  모멘텀 인덱스 :  0.1414786733341733 flag :  True signal :  buy SPY
날짜 :  2006-05-31  모멘텀 인덱스 :  0.11981247253277072 flag :  True signal :  buy SPY
날짜 :  2006-06-30  모멘텀 인덱스 :  0.08443975104335921 flag :  True signal :  buy SPY
날짜 :  2006-07-31  모멘텀 인덱스 :  0.047200906112251806 flag :  True signal :  buy SPY
날짜 :  2006-08-31  모멘텀 인덱스 :  0.061844629466735634 flag :  True signal :  buy SPY
날짜 :  2006-09-29  모멘텀 인덱스 :  0.0763783588186131 flag :  True signal :  buy SPY
날짜 :  2006-10-31  모멘텀 인덱스 :  0.1322202085375661 flag :  True signal :  buy SPY
날짜 :  2006-11-30  모멘텀 인덱스 :  0.11873365348914278 flag :  True signal :  buy SPY
날짜 :  2006-12-29  모멘텀 인덱스 :  0.14316703255204088 flag :  True signal :  buy SPY
날짜 :  2007-01-31  모멘텀 인덱스 :  0.1312854954476106 flag :  True signal :  buy SPY
날짜 :  2007-02-28  모멘텀 인덱스 :  0.14176358685676704 flag :  True signal :  buy SPY
날짜 :  2007-03-30  모멘텀 인덱스 :  0.10119067812318638 flag :  True signal :  buy SPY
날짜 :  2007-04-30  모멘텀 인덱스 :  0.10005667262647377 flag :  True signal :  buy SPY
날짜 :  2007-05-31  모멘텀 인덱스 :  0.1844614525376993 flag :  True signal :  buy SPY
날짜 :  2007-06-29  모멘텀 인덱스 :  0.22145279471930657 flag :  True signal :  buy SPY
날짜 :  2007-07-31  모멘텀 인덱스 :  0.1982283765631614 flag :  True signal :  buy SPY
날짜 :  2007-08-31  모멘텀 인덱스 :  0.1359227989117393 flag :  True signal :  buy SPY
날짜 :  2007-09-28  모멘텀 인덱스 :  0.12025144265100018 flag :  True signal :  buy SPY
날짜 :  2007-10-31  모멘텀 인덱스 :  0.12806787251639906 flag :  True signal :  buy SPY
날짜 :  2007-11-30  모멘텀 인덱스 :  0.12107888670206957 flag :  True signal :  buy SPY
날짜 :  2007-12-31  모멘텀 인덱스 :  0.06343734580249505 flag :  True signal :  buy SPY
날짜 :  2008-01-31  모멘텀 인덱스 :  0.03588260048242242 flag :  True signal :  buy SPY
날짜 :  2008-02-29  모멘텀 인덱스 :  -0.007273340803481632 flag :  False signal :
날짜 :  2008-03-31  모멘텀 인덱스 :  -0.044007148393737316 flag :  False signal :
날짜 :  2008-04-30  모멘텀 인덱스 :  -0.09274353626677045 flag :  False signal :
날짜 :  2008-05-30  모멘텀 인덱스 :  -0.08068476991727935 flag :  False signal :
날짜 :  2008-06-30  모멘텀 인덱스 :  -0.052941242910722 flag :  False signal :
날짜 :  2008-07-31  모멘텀 인덱스 :  -0.10403969762860577 flag :  False signal :
날짜 :  2008-08-29  모멘텀 인덱스 :  -0.12334011966872827 flag :  False signal :
날짜 :  2008-09-30  모멘텀 인덱스 :  -0.14297222131440768 flag :  False signal :
날짜 :  2008-10-31  모멘텀 인덱스 :  -0.23407228558454973 flag :  False signal :
날짜 :  2008-11-28  모멘텀 인덱스 :  -0.33482968335384367 flag :  False signal :
날짜 :  2008-12-31  모멘텀 인덱스 :  -0.3740819216350141 flag :  False signal :
날짜 :  2009-01-30  모멘텀 인덱스 :  -0.3272760819874664 flag :  False signal :
날짜 :  2009-02-27  모멘텀 인덱스 :  -0.3661359941825554 flag :  False signal :
날짜 :  2009-03-31  모멘텀 인덱스 :  -0.4291389876228947 flag :  False signal :
날짜 :  2009-04-30  모멘텀 인덱스 :  -0.40971495248502554 flag :  False signal :
날짜 :  2009-05-29  모멘텀 인덱스 :  -0.36073556053304867 flag :  False signal :
날짜 :  2009-06-30  모멘텀 인덱스 :  -0.2616610957669585 flag :  False signal :
날짜 :  2009-07-31  모멘텀 인덱스 :  -0.2554546845367992 flag :  False signal :
날짜 :  2009-08-31  모멘텀 인덱스 :  -0.21208326394684085 flag :  False signal :
날짜 :  2009-09-30  모멘텀 인덱스 :  -0.09803679482275574 flag :  False signal :
날짜 :  2009-10-30  모멘텀 인덱스 :  0.11874591602744133 flag :  True signal :  buy SPY
날짜 :  2009-11-30  모멘텀 인덱스 :  0.17932688990679213 flag :  True signal :  buy SPY
날짜 :  2009-12-31  모멘텀 인덱스 :  0.23983512023221487 flag :  True signal :  buy SPY
날짜 :  2010-01-29  모멘텀 인덱스 :  0.37655251178810545 flag :  True signal :  buy SPY
날짜 :  2010-02-26  모멘텀 인덱스 :  0.4862170336914984 flag :  True signal :  buy SPY
날짜 :  2010-03-31  모멘텀 인덱스 :  0.41471919507275734 flag :  True signal :  buy SPY
날짜 :  2010-04-30  모멘텀 인덱스 :  0.36521707235092693 flag :  True signal :  buy SPY
날짜 :  2010-05-28  모멘텀 인덱스 :  0.30977591923401504 flag :  True signal :  buy SPY
날짜 :  2010-06-30  모멘텀 인덱스 :  0.20649862503331629 flag :  True signal :  buy SPY
날짜 :  2010-07-30  모멘텀 인덱스 :  0.06464465658172802 flag :  True signal :  buy SPY
날짜 :  2010-08-31  모멘텀 인덱스 :  0.09684348341617777 flag :  True signal :  buy SPY
날짜 :  2010-09-30  모멘텀 인덱스 :  0.011637499941539176 flag :  True signal :  buy SPY
날짜 :  2010-10-29  모멘텀 인덱스 :  0.12384029093099591 flag :  True signal :  buy SPY
날짜 :  2010-11-30  모멘텀 인덱스 :  0.09906340735959307 flag :  True signal :  buy SPY
날짜 :  2010-12-31  모멘텀 인덱스 :  0.07846362532857998 flag :  True signal :  buy SPY
날짜 :  2011-01-31  모멘텀 인덱스 :  0.19395285509075522 flag :  True signal :  buy SPY
날짜 :  2011-02-28  모멘텀 인덱스 :  0.18481207087333473 flag :  True signal :  buy SPY
날짜 :  2011-03-31  모멘텀 인덱스 :  0.15561572146890734 flag :  True signal :  buy SPY
날짜 :  2011-04-29  모멘텀 인덱스 :  0.13814735880393747 flag :  True signal :  buy SPY
날짜 :  2011-05-31  모멘텀 인덱스 :  0.2721909927619406 flag :  True signal :  buy SPY
날짜 :  2011-06-30  모멘텀 인덱스 :  0.32656179484035963 flag :  True signal :  buy SPY
날짜 :  2011-07-29  모멘텀 인덱스 :  0.220801078037417 flag :  True signal :  buy SPY
날짜 :  2011-08-31  모멘텀 인덱스 :  0.2527278375158051 flag :  True signal :  buy SPY
날짜 :  2011-09-30  모멘텀 인덱스 :  0.08655254990240868 flag :  True signal :  buy SPY
날짜 :  2011-10-31  모멘텀 인덱스 :  -0.02608225263360664 flag :  False signal :
날짜 :  2011-11-30  모멘텀 인덱스 :  0.08021807725374974 flag :  True signal :  buy SPY
날짜 :  2011-12-30  모멘텀 인덱스 :  0.008413581830869044 flag :  True signal :  buy SPY
날짜 :  2012-01-31  모멘텀 인덱스 :  -0.004251306713034975 flag :  False signal :
날짜 :  2012-02-29  모멘텀 인덱스 :  0.0069474605121402355 flag :  True signal :  buy SPY
날짜 :  2012-03-30  모멘텀 인덱스 :  0.050528613100580655 flag :  True signal :  buy SPY
날짜 :  2012-04-30  모멘텀 인덱스 :  0.05379785306464968 flag :  True signal :  buy SPY
날짜 :  2012-05-31  모멘텀 인덱스 :  0.05863511028417667 flag :  True signal :  buy SPY
날짜 :  2012-06-29  모멘텀 인덱스 :  0.012132311807995677 flag :  True signal :  buy SPY
날짜 :  2012-07-31  모멘텀 인덱스 :  0.07470512245766847 flag :  True signal :  buy SPY
날짜 :  2012-08-31  모멘텀 인덱스 :  0.1506772869586228 flag :  True signal :  buy SPY
날짜 :  2012-09-28  모멘텀 인덱스 :  0.26749546638718225 flag :  True signal :  buy SPY
날짜 :  2012-10-31  모멘텀 인덱스 :  0.17173600104654296 flag :  True signal :  buy SPY
날짜 :  2012-11-30  모멘텀 인덱스 :  0.1551060389467651 flag :  True signal :  buy SPY
날짜 :  2012-12-31  모멘텀 인덱스 :  0.14963176196566308 flag :  True signal :  buy SPY
날짜 :  2013-01-31  모멘텀 인덱스 :  0.10849706101557666 flag :  True signal :  buy SPY
날짜 :  2013-02-28  모멘텀 인덱스 :  0.116767456031182 flag :  True signal :  buy SPY
날짜 :  2013-03-28  모멘텀 인덱스 :  0.09577241080043208 flag :  True signal :  buy SPY
날짜 :  2013-04-30  모멘텀 인덱스 :  0.14502365079563906 flag :  True signal :  buy SPY
날짜 :  2013-05-31  모멘텀 인덱스 :  0.24158706297000232 flag :  True signal :  buy SPY
날짜 :  2013-06-28  모멘텀 인덱스 :  0.22133698320724648 flag :  True signal :  buy SPY
날짜 :  2013-07-31  모멘텀 인덱스 :  0.19095054765103603 flag :  True signal :  buy SPY
날짜 :  2013-08-30  모멘텀 인덱스 :  0.22188368428063887 flag :  True signal :  buy SPY
날짜 :  2013-09-30  모멘텀 인덱스 :  0.15593216448742764 flag :  True signal :  buy SPY
날짜 :  2013-10-31  모멘텀 인덱스 :  0.21461769332708847 flag :  True signal :  buy SPY
날짜 :  2013-11-29  모멘텀 인덱스 :  0.263711087817023 flag :  True signal :  buy SPY
날짜 :  2013-12-31  모멘텀 인덱스 :  0.2896420997546958 flag :  True signal :  buy SPY
날짜 :  2014-01-31  모멘텀 인덱스 :  0.25864736461780535 flag :  True signal :  buy SPY
날짜 :  2014-02-28  모멘텀 인덱스 :  0.19898410053314897 flag :  True signal :  buy SPY
날짜 :  2014-03-31  모멘텀 인덱스 :  0.2076993426910556 flag :  True signal :  buy SPY
날짜 :  2014-04-30  모멘텀 인덱스 :  0.19476365225022518 flag :  True signal :  buy SPY
날짜 :  2014-05-30  모멘텀 인덱스 :  0.17532012633416127 flag :  True signal :  buy SPY
날짜 :  2014-06-30  모멘텀 인덱스 :  0.21886007703003996 flag :  True signal :  buy SPY

In [12]:
book.tail(25)

             Adj Close   STD_YM    trade
Date
2019-05-20  282.575653  2019-05  buy SPY
2019-05-21  285.123260  2019-05  buy SPY
2019-05-22  284.247528  2019-05  buy SPY
2019-05-23  280.774414  2019-05  buy SPY
2019-05-24  281.411316  2019-05  buy SPY
2019-05-28  278.794037  2019-05  buy SPY
2019-05-29  276.923126  2019-05  buy SPY
2019-05-30  277.679443  2019-05  buy SPY
2019-05-31  273.937653  2019-05  buy SPY
2019-06-03  273.241058  2019-06  buy SPY
2019-06-04  279.172211  2019-06  buy SPY
2019-06-05  281.590424  2019-06  buy SPY
2019-06-06  283.421509  2019-06  buy SPY
2019-06-07  286.257721  2019-06  buy SPY
2019-06-10  287.571350  2019-06  buy SPY
2019-06-11  287.501678  2019-06  buy SPY
2019-06-12  286.994171  2019-06  buy SPY
2019-06-13  288.178375  2019-06  buy SPY
2019-06-14  287.859955  2019-06  buy SPY
2019-06-17  287.969391  2019-06  buy SPY
2019-06-18  290.984741  2019-06  buy SPY
2019-06-19  291.641541  2019-06  buy SPY
2019-06-20  294.427979  2019-06  buy SPY
2019-06-21  294.000000  2019-06  buy SPY
2019-06-24  293.640015  2019-06  buy SPY

In [14]:
def returns(book, ticker):
    # 손익 계산
    rtn = 1.0
    book['return'] = 1
    buy = 0.0
    sell = 0.0
    for i in book.index:
        if book.loc[i, 'trade'] == 'buy '+ ticker and book.shift(1).loc[i,'trade'] == '' :     # long 진입
            buy = book.loc[i, 'Adj Close']
            print('진입일 : ',i, 'long 진입가격 : ', buy)
        elif book.loc[i, 'trade'] == 'buy '+ ticker and book.shift(1).loc[i,'trade'] == 'buy '+ ticker :
            # 보유중  
            current = book.loc[i, 'Adj Close']
            rtn = (current - buy) / buy + 1
            book.loc[i, 'return'] = rtn
            
        elif book.loc[i, 'trade'] == '' and book.shift(1).loc[i, 'trade'] == 'buy '+ticker:     # long 청산
            sell = book.loc[i, 'Adj Close']
            rtn = (sell - buy) / buy + 1 # 손익 계산
            book.loc[i, 'return'] = rtn
            print('청산일 : ',i, 'long 진입가격 : ', buy, ' |  long 청산가격 : ', \
                  sell, ' | return:', round(rtn, 4))

        if book.loc[i, 'trade'] == '':     # zero position
            buy = 0.0
            sell = 0.0
            current = 0.0

    acc_rtn = 1.0
    for i in book.index:
        if book.loc[i, 'trade'] == '' and book.shift(1).loc[i, 'trade'] == 'buy '+ticker:     # long 청산시
            rtn = book.loc[i, 'return']
            acc_rtn = acc_rtn * rtn # 누적수익률 계산
            book.loc[i:, 'acc return'] = acc_rtn

    print ('Accunulated return :', round(acc_rtn, 4))
    return (round(acc_rtn, 4))

returns(book,ticker)

진입일 :  1994-01-31 long 진입가격 :  30.045222999999996
청산일 :  1994-12-30 long 진입가격 :  30.045222999999996  |  long 청산가격 :  29.148033  | return: 0.9701
진입일 :  1995-02-28 long 진입가격 :  31.357141
청산일 :  2000-12-29 long 진입가격 :  31.357141  |  long 청산가격 :  92.002388  | return: 2.934
진입일 :  2001-02-28 long 진입가격 :  86.926689
청산일 :  2001-03-30 long 진입가격 :  86.926689  |  long 청산가격 :  82.055542  | return: 0.944
진입일 :  2003-07-31 long 진입가격 :  72.26248199999999
청산일 :  2008-02-29 long 진입가격 :  72.26248199999999  |  long 청산가격 :  105.568001  | return: 1.4609
진입일 :  2009-10-30 long 진입가격 :  85.141289
청산일 :  2011-10-31 long 진입가격 :  85.141289  |  long 청산가격 :  107.309486  | return: 1.2604
진입일 :  2011-11-30 long 진입가격 :  106.873421
청산일 :  2012-01-31 long 진입가격 :  106.873421  |  long 청산가격 :  112.998047  | return: 1.0573
진입일 :  2012-02-29 long 진입가격 :  117.902817
청산일 :  2015-10-30 long 진입가격 :  117.902817  |  long 청산가격 :  193.002396  | return: 1.637
진입일 :  2015-11-30 long 진입가격 :  193.707825
청산일 :  2016-02-29 long 진입가격 :  193.707825  |  long 청산가격 :  180.733292  | return: 0.933
진입일 :  2016-04-29 long 진입가격 :  193.650711
청산일 :  2016-05-31 long 진입가격 :  193.650711  |  long 청산가격 :  196.945023  | return: 1.017
진입일 :  2016-06-30 long 진입가격 :  197.629578
청산일 :  2019-01-31 long 진입가격 :  197.629578  |  long 청산가격 :  267.445465  | return: 1.3533
진입일 :  2019-02-28 long 진입가격 :  276.114929
Accunulated return : 10.9953

10.9953

In [15]:
book.loc['1994-11-31':,]

             Adj Close   STD_YM    trade    return  acc return
Date
1994-12-01   28.649719  1994-12  buy SPY  0.953553         NaN
1994-12-02   28.917469  1994-12  buy SPY  0.962465         NaN
1994-12-05   28.947224  1994-12  buy SPY  0.963455         NaN
1994-12-06   28.967051  1994-12  buy SPY  0.964115         NaN
1994-12-07   28.758799  1994-12  buy SPY  0.957184         NaN
...                ...      ...      ...       ...         ...
2019-06-18  290.984741  2019-06  buy SPY  1.053854   10.995336
2019-06-19  291.641541  2019-06  buy SPY  1.056232   10.995336
2019-06-20  294.427979  2019-06  buy SPY  1.066324   10.995336
2019-06-21  294.000000  2019-06  buy SPY  1.064774   10.995336
2019-06-24  293.640015  2019-06  buy SPY  1.063470   10.995336

[6183 rows x 5 columns]